In [167]:
# Display the first few lines of the file in raw form
with open('spam.csv', 'r', encoding='latin-1') as file:
    for i in range(5):
        print(file.readline())


v1,v2,,,

ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,

ham,Ok lar... Joking wif u oni...,,,

spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,

ham,U dun say so early hor... U c already then say...,,,



In [168]:
import pandas as pd

# Load the CSV file, specifying the correct separator and encoding
messages = pd.read_csv('spam.csv', sep=',', header=0, encoding='latin-1')

# Display the first few rows of the DataFrame
print("Original DataFrame:")
print(messages.head())

# Select only the relevant columns (first two columns)
messages = messages.iloc[:, [0, 1]]  # Keep only the first two columns

# Rename the columns
messages.columns = ['label', 'message']

# Display the cleaned DataFrame
print("\nCleaned DataFrame:")
print(messages.head())


Original DataFrame:
     v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  

Cleaned DataFrame:
  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...


In [169]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [170]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [171]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [172]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

### Creating the Bag of Words Model

In [173]:
#converting dependent features to zero and one

y= pd.get_dummies( messages['label'], dtype=int)
y= y.iloc[:, 0].values

In [174]:
#train test split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(corpus,y, test_size= 0.20)

In [175]:
x_train

['heehe funni tho',
 'ok pa noth problem',
 'love brother time talk english grin say hey muhommad penni say hello across sea',
 'stop know well',
 'write wat',
 'work time',
 'thank rington order refer number x mobil charg tone arriv pleas call custom servic [colour red]text[ colour]txtstar',
 'get lion england tone repli lionm mono lionp poli go www rington co uk origin n best tone gbp network oper rate appli',
 'anybodi number still thought tact way ask alex',
 'reach home n bath liao u call',
 'reason spoken year anyway great week best exam',
 'togeth thinkin',
 'sunshin hol claim ur med holiday send stamp self address envelop drink us uk po box bray wicklow eir quiz start saturday unsub stop',
 'shall get pouch',
 'feel like tri kadeem v',
 'hi kindli give us back document submit loan stapati',
 'wif buy tix lar',
 'greatest test courag earth bear defeat without lose heart gn tc',
 'good day pray remov teeth pain maintain stuff',
 'thank rington order refer number x mobil charg ton

In [176]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500, ngram_range=(1,2))

In [177]:
x_train = cv.fit_transform(x_train).toarray()
x_test = cv.transform(x_test).toarray()

In [178]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
x_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [179]:
cv.vocabulary_

{'funni': 741,
 'tho': 2109,
 'ok': 1461,
 'pa': 1507,
 'noth': 1439,
 'problem': 1639,
 'love': 1191,
 'brother': 226,
 'time': 2121,
 'talk': 2050,
 'grin': 839,
 'say': 1789,
 'hey': 910,
 'hello': 907,
 'across': 11,
 'sea': 1800,
 'say hello': 1791,
 'across sea': 12,
 'stop': 1990,
 'know': 1068,
 'well': 2368,
 'know well': 1071,
 'write': 2446,
 'wat': 2333,
 'work': 2426,
 'thank': 2091,
 'rington': 1748,
 'order': 1493,
 'refer': 1705,
 'number': 1446,
 'mobil': 1319,
 'charg': 325,
 'tone': 2147,
 'arriv': 98,
 'pleas': 1576,
 'call': 246,
 'custom': 456,
 'servic': 1839,
 'colour': 376,
 'red': 1701,
 'text': 2079,
 'thank rington': 2094,
 'rington order': 1751,
 'refer number': 1706,
 'number mobil': 1449,
 'mobil charg': 1321,
 'charg tone': 326,
 'tone arriv': 2148,
 'arriv pleas': 99,
 'pleas call': 1577,
 'call custom': 251,
 'custom servic': 459,
 'get': 759,
 'lion': 1150,
 'england': 596,
 'repli': 1721,
 'poli': 1598,
 'go': 783,
 'www': 2452,
 'co': 360,
 'uk': 22

In [180]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [181]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [182]:
from sklearn.naive_bayes import MultinomialNB

In [183]:
spam_detection_model = MultinomialNB().fit(x_train, y_train)

In [184]:
spam_detection_model

MultinomialNB()

In [185]:
y_pred = spam_detection_model.predict(x_test)

In [186]:
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1])

In [187]:
from sklearn.metrics import accuracy_score, classification_report

In [188]:
y_pred.shape

(1115,)

In [189]:
y_test.shape

(1115,)

In [190]:
accuracy_score(y_test, y_pred)

0.979372197309417

In [191]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.90      0.93       158
           1       0.98      0.99      0.99       957

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



### Creating the TF-IDF Model

In [192]:
#train test split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(corpus,y, test_size= 0.20)

In [193]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [194]:
tv= TfidfVectorizer(max_features=2500, ngram_range=(1,2))
x_train = tv.fit_transform(x_train).toarray()
x_test = tv.transform(x_test).toarray()

In [195]:
tv

TfidfVectorizer(max_features=2500, ngram_range=(1, 2))

In [196]:
spam_tfidf_model = MultinomialNB().fit(x_train, y_train)

In [197]:
y_pred2 = spam_tfidf_model.predict(x_test)

In [198]:
y_pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [199]:
accuracy_score( y_test, y_pred2)

0.9748878923766816

In [200]:
print(classification_report( y_test, y_pred2))

              precision    recall  f1-score   support

           0       1.00      0.82      0.90       155
           1       0.97      1.00      0.99       960

    accuracy                           0.97      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.98      0.97      0.97      1115

